### ISSUE TITLE
[BUG] OwO filter crashes the game when triggered.

### ISSUE THREAD

**Issue by TNTea** [DarkKronicle/AdvancedChatFilters#1]
**Description**
Every text just displays its ID instead of using the localized string.

**Minecraft Info**
Version: 1.17.1
- Fabric Loader 0.11.6
- Fabric API 0.37.2+1.17
- MaLiLib 0.10.0-dev.24
- Architectury 2.3.24
- Mod Menu 2.0.4
- Sodium 0.3.0+build.5
- Lithium 0.7.3
- Borderless Mining 1.0.6
- MiniHUD 0.19.0
- Roughly Enough Items 6.0.267-alpha
- VoxelMap 1.10.15
- Litematica 0.0.0-dev.20210713.103711
- Command Macros 1.5.2-1.17

- **AdvancedChatCore 1.0.1-1.17.1 (beta5)**
- **AdvancedChatFilters 1.0.0**

**To Reproduce**

1. Join a world.
2. Setup a filter as seen in the first screenshot.
3. Enable the filter.
4. Type test.

**Expected behavior**
Don't throw an exception an crash the game.

**Screenshots**
![image](https://user-images.githubusercontent.com/43808589/129450399-ec1aad3c-840f-4dbe-a28e-2bf25c20ac14.png)

![image](https://user-images.githubusercontent.com/43808589/129450342-36ec468e-6018-4c23-b8bc-985cb6f1c571.png)

**Comment by DarkKronicle** [comment]
Should work now
