### ISSUE TITLE
[FEATURE] Multiple Matches per Filter

### ISSUE THREAD

**Issue by Andreas-Coding** [DarkKronicle/AdvancedChatFilters#5]
**Is your feature request related to a problem? Please describe.**
Replacing various things with the same thing, that would require you to manipulate the same regex over and over is tedious.

**Describe the solution you'd like**
Having a similar Match system to what exists for Chat Tabs.

**Additional context**
![image](https://user-images.githubusercontent.com/56117677/141681263-adc2b400-6fd2-40f4-b218-170bb394280b.png)
oh and fix that button xD

**Comment by DarkKronicle** [comment]
Will now be in Konstruct.
