### ISSUE TITLE
[BUG] RegEx only uses the first match of a group when substituting

### ISSUE THREAD

**Issue by SnazzGass** [DarkKronicle/AdvancedChatFilters#6]
**Describe the bug**
when matching multiple sections with a single capture, only the first match gets substituted.

**Minecraft Info**
Minecraft information:
- AdvancedChatCore 1.2.0 - 1.17.1
- AdvancedChatFilters 1.0.1 - 1.17.1
- AdvancedChatHUD 1.0.2 - 1.17.1
- Fabric 0.11.7 - 1.17.1

**To Reproduce**
enter (foo|bar) in string to find and set the mode to regex with replace match. This regex string should match and capture either "foo" or "bar", and substitute it into $1, resulting in "[foo]" or "[bar]" respectively
![image](https://user-images.githubusercontent.com/45057060/141852664-f6cc76f3-98d4-451e-aa6c-426539e4ec0c.png)

type in chat "foo bar"

bruh moment
![image](https://user-images.githubusercontent.com/45057060/141852820-9136e555-0470-4d59-a879-73223b7ed1da.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/45057060/141852933-3cf08716-9cb7-4aea-943b-d9518316ff27.png)

**Comment by DarkKronicle** [comment]
Thanks for the detailed report! I remember groups being weird so hopefully this is a simple fix.

**Comment by DarkKronicle** [comment]
Changed how RegEx filters work a bit. Can you check to see if this is fixed in the new update?

**Comment by SnazzGass** [comment]
I cant test if this fix worked because of the new bug https://github.com/DarkKronicle/AdvancedChatFilters/issues/8
