### ISSUE TITLE
[FEATURE] Regex Enhancements

### ISSUE THREAD

**Issue by SnazzGass** [DarkKronicle/AdvancedChatFilters#7]
Most of these ideas have come from the chatflow mod, but I also have some original enhancements here.
These ideas focus on making the regex nicer to use.

1. Add a link somewhere that will take you to some regex documentation, and also minecraft formatting codes documentation, or include some basic documentation in game.

2. Make the regex entry field bigger, and allow multiple rows and comments that get stripped out before it goes to the parser. This overall would vastly increase the utility because the regex could actually be legible.

3. Add the ability to enter in some text and see a live preview of it after it has been parsed; Get rid of the annoying cycle of exiting out of the menu, typing something in chat, going back into the menu and changing one character at a time.

3.b. Add the ability to copy a message from your chat into the regex previewer so you can see the character representations of the actual messages you are receiving and debug your regex.

Here is a screenshot of the chatflow implementation:
![image](https://user-images.githubusercontent.com/45057060/141888234-4dc956d9-f63e-4353-96bc-e649bebfb657.png)

**Comment by DarkKronicle** [comment]
Added 3 and part of 2. I'll look a bit more into comments, but it may be more left to Konstruct. Planning on adding 1 once the wiki is good. Planned to be released soon.
![image](https://user-images.githubusercontent.com/38167691/151715117-92d6c131-4675-40cf-bedf-a6f358ce4f4b.png)
