### ISSUE TITLE
[BUG] Special Characters are matched literally

### ISSUE THREAD

**Issue by SnazzGass** [DarkKronicle/AdvancedChatFilters#8]
**Describe the bug**
Don't know how this didn't get caught sooner as the regex matcher is completely broken and will only match literals.

**Minecraft Info**
Minecraft information:
- AdvancedChatFilters 1.1.0

**To Reproduce**
Set up a filter like this

![2021-11-19_20 34 45](https://user-images.githubusercontent.com/45057060/142714543-13c116fd-2041-47dd-acd3-ba3b23d82e56.png)

As you can see, it doesn't match the first foo because it will only match literal strings. but when it does match it, the capture group seems to work.
![2021-11-19_20 34 09](https://user-images.githubusercontent.com/45057060/142714564-b84dabb4-ae6b-4251-8dd3-b67cffe98c0f.png)

**Additional notes**
It seems like most of the special characters aren't possible to use right now because a character like \s would have to match both ' ' and the literal '\s' at the same time.
Some special cases where a special character can match itself still work, for instance . will still match '.' but not any other character.

**Comment by Fury-101** [comment]
Seems to be a relatively new issue

**Comment by SnazzGass** [comment]
yeah, Just appeared in 1.1.0
