### ISSUE TITLE
[BUG] Background/Text Color doesn't save

### ISSUE THREAD

**Issue by Toseflo** [DarkKronicle/AdvancedChatFilters#9]
**Describe the bug**
When you create a new filter and try to change the background/text color for replaced text, the value doesn't save. When you close the filter and open it again, you can see that the color reset back to #FFFFFFFF

**Minecraft Info**
Minecraft information:
- AdvancedChatCore-1.3.1
- AdvancedChatFilters-1.1.0

**To Reproduce**
Try to create a filter which replaces the text color. Notice how the value resets to #FFFFFFFF when you open the filter again

**Comment by DarkKronicle** [comment]
Have you tried hitting enter on the text box? If that's the problem I should probably get around to live updates.

**Comment by Toseflo** [comment]
Yes I tried hitting enter. Even regenerated my AdvancedChat Config to see if it makes a difference, but the color value still won't save. Here is a video which shows the bug https://gyazo.com/75cd1dda4ad68d0d0df1e4827757d886 . Notice how the String to Find is saved when I reopen the filter config, but the color resets to #FFFFFFFF

**Comment by DarkKronicle** [comment]
Fixed now
